package model

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ShortenedData) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "original":
			z.Orig, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Orig")
				return
			}
		case "hash":
			z.Hash, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Hash")
				return
			}
		case "short":
			z.Short, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Short")
				return
			}
		case "expiry":
			z.Expiry, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "Expiry")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ShortenedData) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "original"
	err = en.Append(0x84, 0xa8, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteString(z.Orig)
	if err != nil {
		err = msgp.WrapError(err, "Orig")
		return
	}
	// write "hash"
	err = en.Append(0xa4, 0x68, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.Hash)
	if err != nil {
		err = msgp.WrapError(err, "Hash")
		return
	}
	// write "short"
	err = en.Append(0xa5, 0x73, 0x68, 0x6f, 0x72, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Short)
	if err != nil {
		err = msgp.WrapError(err, "Short")
		return
	}
	// write "expiry"
	err = en.Append(0xa6, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79)
	if err != nil {
		return
	}
	err = en.WriteTime(z.Expiry)
	if err != nil {
		err = msgp.WrapError(err, "Expiry")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ShortenedData) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "original"
	o = append(o, 0x84, 0xa8, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c)
	o = msgp.AppendString(o, z.Orig)
	// string "hash"
	o = append(o, 0xa4, 0x68, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.Hash)
	// string "short"
	o = append(o, 0xa5, 0x73, 0x68, 0x6f, 0x72, 0x74)
	o = msgp.AppendString(o, z.Short)
	// string "expiry"
	o = append(o, 0xa6, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79)
	o = msgp.AppendTime(o, z.Expiry)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ShortenedData) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "original":
			z.Orig, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Orig")
				return
			}
		case "hash":
			z.Hash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Hash")
				return
			}
		case "short":
			z.Short, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Short")
				return
			}
		case "expiry":
			z.Expiry, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Expiry")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ShortenedData) Msgsize() (s int) {
	s = 1 + 9 + msgp.StringPrefixSize + len(z.Orig) + 5 + msgp.StringPrefixSize + len(z.Hash) + 6 + msgp.StringPrefixSize + len(z.Short) + 7 + msgp.TimeSize
	return
}
